version: "3.9"

services:
  adonis-api:
    build: .
    container_name: docker-adonis-api
    volumes:
      - "./api:/usr/src/api"
    ports:
      - "3333:3333"

    environment:
      - CHOKIDAR_USEPOLLING=1
    env_file: 
      - ./api/.env
    networks:
      - app-network
    depends_on:
      - mysql-adonis

  mysql-adonis:
    container_name: 'mysql-adonis'
    image: mysql:5.7
    command: --disable-partition-engine-check --init-file /docker-entrypoint-initdb.d/init.sql
    volumes: 
      - ./data:/var/lib/mysql/
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - app-network
    ports: 
      - "3307:3306"
    expose: 
      - "3307"
    environment: 
      MYSQL_DATABASE: lubycash
      MYSQL_HOST: localhost
      MYSQL_USER: armando
      MYSQL_PASSWORD: 12341234
      MYSQL_ROOT_PASSWORD: 12341234

networks:
  app-network:
    driver: bridge
    ipam: 
      driver: default
      config: 
        - subnet: 172.23.0.0/16